//! Bit-identical port of `shared/src/cardVocab.ts`.
//!
//! The vocab is generated by `npm run sim:build-card-vocab` and stored at
//! `shared/src/cardVocab.json`. It maps card-id strings → small integer
//! indices used by the Python embedding table. Order is load-bearing:
//! `"FullArtGold"` must precede `"FullArt"` in the suffix-fallback loop
//! because `"FullArt"` is a strict suffix of `"FullArtGold"`.
//!
//! Embedded at compile time via `include_str!` to avoid a runtime read.

use std::sync::OnceLock;

use indexmap::IndexMap;
use serde::Deserialize;

const VOCAB_JSON: &str = include_str!("../../../../../shared/src/cardVocab.json");

#[derive(Debug, Deserialize)]
struct VocabFile {
    #[serde(rename = "schemaVersion", default)]
    _schema_version: u32,
    #[serde(rename = "unknownIndex", default)]
    unknown_index: u32,
    #[serde(rename = "vocabSize")]
    vocab_size: u32,
    #[serde(rename = "indexById")]
    index_by_id: IndexMap<String, u32>,
}

#[derive(Debug)]
pub struct CardVocab {
    pub unknown_index: u32,
    pub vocab_size: u32,
    pub index_by_id: IndexMap<String, u32>,
}

/// Suffix fallback order — strict-suffix-first, matching
/// `cardVocab.ts:28` SUFFIX_TOKENS.
const SUFFIX_TOKENS: [&str; 4] = ["FullArtGold", "FullArt", "UncommonPlus", "Ex"];

pub fn card_vocab() -> &'static CardVocab {
    static V: OnceLock<CardVocab> = OnceLock::new();
    V.get_or_init(load)
}

fn load() -> CardVocab {
    let parsed: VocabFile = serde_json::from_str(VOCAB_JSON).expect("cardVocab.json must parse");
    CardVocab {
        unknown_index: parsed.unknown_index,
        vocab_size: parsed.vocab_size,
        index_by_id: parsed.index_by_id,
    }
}

/// Mirror of `cardVocab.ts:30` `cardVocabIndex`. Returns
/// `unknownIndex` (default 0) when no direct match and no suffix fallback
/// hits.
pub fn card_vocab_index(card_id: Option<&str>) -> u32 {
    let Some(id) = card_id else {
        return 0;
    };
    if id.is_empty() {
        return 0;
    }
    let v = card_vocab();
    if let Some(&direct) = v.index_by_id.get(id) {
        return direct;
    }
    for suffix in SUFFIX_TOKENS {
        if id.ends_with(suffix) {
            let base = &id[..id.len() - suffix.len()];
            if let Some(&base_index) = v.index_by_id.get(base) {
                return base_index;
            }
        }
    }
    v.unknown_index
}

pub fn card_vocab_size() -> u32 {
    card_vocab().vocab_size
}

pub fn card_vocab_unknown_index() -> u32 {
    card_vocab().unknown_index
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn null_or_empty_returns_zero() {
        assert_eq!(card_vocab_index(None), 0);
        assert_eq!(card_vocab_index(Some("")), 0);
    }

    #[test]
    fn known_base_card_maps_to_nonzero() {
        // matikanetannhauserBasic is the first base card in cards.json;
        // it must be in the vocab.
        let idx = card_vocab_index(Some("matikanetannhauserBasic"));
        assert!(idx > 0, "expected nonzero index, got {}", idx);
    }

    #[test]
    fn variant_falls_back_to_base() {
        // Variants share the base card's vocab index via suffix fallback.
        let base = card_vocab_index(Some("matikanetannhauserBasic"));
        let full_art = card_vocab_index(Some("matikanetannhauserBasicFullArt"));
        let uncommon = card_vocab_index(Some("matikanetannhauserBasicUncommonPlus"));
        // FullArt variants exist for the base list — check it falls back.
        assert_eq!(full_art, base);
        assert_eq!(uncommon, base);
    }

    #[test]
    fn fullartgold_takes_precedence_over_fullart() {
        // Construct an id ending in FullArtGold whose base is in vocab.
        // Pick a trainer card from the fullArtGold list. After expansion
        // both `${id}FullArt` and `${id}FullArtGold` exist as catalog ids,
        // but cardVocab.json only stores base ids. The strict-suffix rule
        // ensures we strip FullArtGold first.
        let base = card_vocab_index(Some("etsukoOtonashi"));
        if base > 0 {
            // Only check if etsukoOtonashi is actually in the vocab.
            let gold = card_vocab_index(Some("etsukoOtonashiFullArtGold"));
            assert_eq!(gold, base);
        }
    }

    #[test]
    fn unknown_id_returns_unknown_index() {
        let unk = card_vocab_unknown_index();
        assert_eq!(card_vocab_index(Some("zzz-not-a-real-card-id")), unk);
    }
}
