// Canonical TS-side view of `shared/src/cardVocab.json`. Mirrors
// `card_vocab_index` in `training/uma_ai/features.py` line-for-line so the
// TS observation emitter (R7.b.2 Phase 1) and the Python feature extractor
// produce identical integer ids per cardId.
//
// The JSON file is generated by `npm run sim:build-card-vocab`; index 0 is
// the reserved unknownIndex / padding slot. Suffix handling matches the
// "FullArtGold" before "FullArt" rule (must come first because "FullArt" is
// a suffix of "FullArtGold").

import cardVocabJson from "./cardVocab.json";

type CardVocabFile = {
  schemaVersion: number;
  unknownIndex: number;
  vocabSize: number;
  indexById: Record<string, number>;
  baseIdByVariant?: Record<string, string>;
  orderedIds?: string[];
  suffixOrder?: Record<string, number>;
  hash?: string;
};

const VOCAB = cardVocabJson as CardVocabFile;

// Order is load-bearing: "FullArtGold" must precede "FullArt" because
// "FullArt" is a strict suffix. Mirrors `card_vocab_index` Python line 466.
const SUFFIX_TOKENS = ["FullArtGold", "FullArt", "UncommonPlus", "Ex"] as const;

export function cardVocabIndex(cardId: string | null | undefined): number {
  if (!cardId) return 0;
  const direct = VOCAB.indexById[cardId];
  if (direct !== undefined) return direct;
  for (const suffix of SUFFIX_TOKENS) {
    if (cardId.endsWith(suffix)) {
      const baseId = cardId.slice(0, -suffix.length);
      const baseIndex = VOCAB.indexById[baseId];
      if (baseIndex !== undefined) return baseIndex;
    }
  }
  return VOCAB.unknownIndex ?? 0;
}

export function cardVocabSize(): number {
  return VOCAB.vocabSize;
}

export function cardVocabUnknownIndex(): number {
  return VOCAB.unknownIndex ?? 0;
}
